### ISSUE TITLE
Clocks going crazy

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1333] opened 2016-03-02 16:21 UTC
It happens to me _very_ often that the clocks go completely crazy while playing.
For example, I am playing a game and then my opponent takes a few minutes to make a move [even in easy positions, curious] and meanwhile the clock decreases normally, then he moves and his clock goes negative, then I move and his clock goes back to a higher time than the one it had earlier.

Is this Pychess or FICS? Anyone experienced the same?

**Comment by cajone** [comment] 2016-03-02 16:58
think this is also related to #1092

**Comment by gbtami** [comment] 2016-03-02 20:34
I think #1092 happens only in relayed games, and this is a FICS relay problem, nothing we can do about it.
I'v never seen this issue in played games. It would be good to have a screenshot with a .log to analyze the problem.

**Comment by cajone** [comment] 2016-03-02 20:44
I was thinking about this last time ie #1092. One of the things that crossed my mind to what the problem might be is : 

1) assuming while waiting for a move the displayed clocks are not interacting or getting time updates at all from FICS, but are  ticking down using a local ticker.

2) Given the above statement, is it possible the code we use to decrement the clocks is actually running faster that real time hence when an update arrives from fics ( which contains a time stamp ) the clocks re-adjust to the correct time, but since the algorithm driving the local ticker is running faster, we perceive this jumping of clock times each time we get an update from FICS?

**Comment by gbtami** [comment] 2016-03-10 10:31
After rereading this issue I think this is a simple lag problem of your partner. If you set autoflag on you should get some infobar message  about lagging. Maybe this was not caught. (regression?) Try to check console about lag server messages.

**Comment by massimiliano-leoni** [comment] 2016-04-05 15:22
I noticed that if I issue the `time` command in the console the clocks automagically set to the correct time.

**Comment by gbtami** [comment] 2016-04-05 15:42
It's interesting. We don't parse reply of "time" command at all.

**Comment by massimiliano-leoni** [comment] 2016-04-11 07:34
I have to amend: it does not happen all the times! Sometimes the `time` command adjusts the clocks, sometimes it does nothing.

**Comment by gbtami** [comment] 2016-04-12 21:26
Note to myself: git bisect it!

**Comment by gbtami** [comment] 2016-05-01 10:06
@massimiliano-leoni committed a possible fix. can you test it please?

**Comment by massimiliano-leoni** [comment] 2016-05-01 15:30
I will keep an eye on it!

**Comment by gbtami** [comment] 2016-05-08 10:36
I think this is ok now. If I'm wrong reopen it please.

**Closed as completed by gbtami** 2016-05-08 10:36 UTC
Labels: bug, Critical

**Comment by massimiliano-leoni** [comment] 2016-05-10 11:02
I'll keep an eye on this and report back.
