### ISSUE TITLE
Add a Panel to Preferences to allow board colour change

### ISSUE THREAD

**Issue by cajone** [pychess/pychess#1044] opened 2015-11-15 18:05 UTC
The default colour scheme is great, but it might not suit all others or have certain issues depending on local lighting.

Would be nice to have an ability to change the board colour as per user requirements / likes.

Possible extension to this which I will open an isue ticket at a later stage would to allow texturing of board to give different effects / aesthetics 

(Enhancement request )

**Comment by gbtami** [comment] 2015-11-15 18:10
This is duplicate of #188

**Closed as completed by gbtami** 2015-11-15 18:10 UTC
