### ISSUE TITLE
[feature request] Filter seeks by type

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#991] opened 2015-08-08 08:47 UTC
Let's say I typically play standard rated matches. It would be nice to be able to filter all the seeks and show only those.

**Comment by gbtami** [comment] 2015-08-08 18:54
This is duplicate of #760  Filter FICS seeks/players/games

**Closed as completed by gbtami** 2015-08-08 18:54 UTC
Labels: duplicate

**Comment by massimiliano-leoni** [comment] 2015-08-08 18:57
Oops, sorry for not searching before posting :(
