### ISSUE TITLE
pychess_0.12.4-1_all.deb hangs during FICS game on Linux Mint 17.3 KDE 64-bit

### ISSUE THREAD

**Issue by BriCra17gh** [pychess/pychess#1412] opened 2017-05-06 07:37 UTC
pychess frequently hangs while playing an FICS game. When it is my turn, I can no longer select any of my pieces. However I can select, but not move, the opponent's pieces. I get errors such as the one shown below in my xterm where I started pychess. 

The pychess console continues to work. The pychess menus work, too. So I can offer an adjournment, etc. But if the opponent doesn't accept an adjournment, then I either have to resign or lose on time, even in a winning position.

% pychess

Exception in thread ICGameModel.run:630:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/pychess/Utils/GameModel.py", line 707, in run
    newBoard = self.boards[-1].move(move)
  File "/usr/lib/python2.7/dist-packages/pychess/Utils/Board.py", line 305, in move
    assert self[move.cord0], "%s %s" % (move, self.asFen())
AssertionError: a3b3 8/6k1/8/R3K3/1pPpP1B1/1r1P3P/8/8 b - - 0 52

BriCra

**Comment by gbtami** [comment] 2017-05-06 08:22
Seems to me this is caused by one of the remaining very hard to reproduce and debug threading issues pychess has. To get rid of these problems I'v started to change all threading code to use asyncio in pychess asyncio branch (it will require Python3). engine-engine, human-human and human-engine games are working ok. I'm working on FICS/ICC thereading->asyncio right now.

**Comment by BriCra17gh** [comment] 2017-05-06 08:37
Sounds good. This does not happen all of the time but frequently enough that I'll have to wait for the next version to resume using pychess with FICS. That's a shame because pychess has so many nice features.

Please let me know if you need additional information.

**Comment by gbtami** [comment] 2017-05-15 13:43
@BriCra17gh try latest git version if you can please!
It needs Python3. See the INSTALL file for packages needed.

**Comment by BriCra17gh** [comment] 2017-05-18 03:24
Sure. I can test over the weekend. Thanks for the quick work.

**Comment by BriCra17gh** [comment] 2017-05-22 11:13
I tried to test but didn't get far. Here's what I did and my experience:

Satisfied the dependencies described in INSTALL. 
In github, used github's "clone or download" button to download a zip file. 
Unzipped the file and in the new directory ran 

%  ./pychess 

Got an alert "pychess is discovering your engines. Please wait". It makes no progress. 
Got these messages:

===
Warning: eco.db not found, please run pgn2ecodb.sh
Can't find scoutfish.py See https://github.com/mcostalba/scoutfish
Can't find chess_db.py See https://github.com/mcostalba/chess_db

(pychess:10683): Gtk-WARNING **: Can't set a parent on widget which has a parent

(pychess:10683): Gtk-WARNING **: Unknown property: GtkSpinButton.max-width-chars

(pychess:10683): Gtk-WARNING **: Unknown property: GtkSpinButton.max-width-chars

(pychess:10683): Gtk-WARNING **: Unknown property: GtkSpinButton.max-width-chars

(pychess:10683): Gtk-WARNING **: Unknown property: GtkSpinButton.max-width-chars

(pychess:10683): Gtk-WARNING **: Unknown property: GtkEntry.max-width-chars

(pychess:10683): Gtk-WARNING **: Unknown property: GtkEntry.max-width-chars
Traceback (most recent call last):
  File "/tmp/pychess-master/lib/pychess/Players/PyChess.py", line 11, in <module>
    from pychess.Utils.book import getOpenings  # nopep8
  File "/tmp/pychess-master/lib/pychess/Players/../../pychess/Utils/book.py", line 7, in <module>
    from pychess.System import conf
  File "/tmp/pychess-master/lib/pychess/Players/../../pychess/System/conf.py", line 7, in <module>
    from configparser import RawConfigParser
ImportError: No module named configparser
/tmp/pychess-master/lib/pychess/external/gbulb/transports.py:400: Warning: Invalid file descriptor.

  self._channel.shutdown(True)
/tmp/pychess-master/lib/pychess/external/gbulb/transports.py:384: Warning: Invalid file descriptor.

  self._channel.shutdown(True)

===

Got the pychess window that is unresponsive until I terminate the "discovering engines" alert.

Got many more problems and messages that probably don't make sense to document until I learn how to resolve the above.

BriCra

**Comment by gbtami** [comment] 2017-05-22 22:23
ImportError: No module named configparser
This is strange because configparser is standard Python3 module. It was ConfigParser in Python2 so running git version of pychess in place maybe somehow trying to import something from installed (Python2) pychess package. Try to "sudo apt purge pychess" please!
Unfortunately I wasn't able to reproduce this on Ubuntu 16.04 yet.

**Comment by BriCra17gh** [comment] 2017-05-28 20:08
I executed "sudo apt purge pychess", picked up the latest pychess code (2017-05-28-0819), ensured the dependencies listed in INSTALL were satisfied, and ran

% ./pychess

I still got the hanging alert "pychess is discovering your engines. Please wait".
I forced the alert to close. Another window hangs trying to log into FICS.
And I get the messages shown below. The final three messages result from forcing the main window to close after selecting 'cancel' in the hanging FICS window.

I can test more today and tomorrow if you have any suggestions.

=======================

Warning: eco.db not found, please run pgn2ecodb.sh
Can't find scoutfish.py See https://github.com/mcostalba/scoutfish
Can't find chess_db.py See https://github.com/mcostalba/chess_db

(pychess:32725): Gtk-WARNING **: Can't set a parent on widget which has a parent


(pychess:32725): Gtk-WARNING **: Unknown property: GtkSpinButton.max-width-chars

(pychess:32725): Gtk-WARNING **: Unknown property: GtkSpinButton.max-width-chars

(pychess:32725): Gtk-WARNING **: Unknown property: GtkSpinButton.max-width-chars

(pychess:32725): Gtk-WARNING **: Unknown property: GtkSpinButton.max-width-chars

(pychess:32725): Gtk-WARNING **: Unknown property: GtkEntry.max-width-chars

(pychess:32725): Gtk-WARNING **: Unknown property: GtkEntry.max-width-chars
Traceback (most recent call last):
  File "/tmp/pychess-master-2017-05-28-0819/lib/pychess/widgets/Background.py", line 205, in newTheme
    imgsurface = cairo.ImageSurface.create_from_png(background)
SystemError: error return without exception set
Traceback (most recent call last):
  File "/tmp/pychess-master-2017-05-28-0819/lib/pychess/widgets/Background.py", line 40, in expose
    cairo_create.set_source_surface(surface, 0, 0)
TypeError: must be cairo.Surface, not None
Traceback (most recent call last):
  File "/tmp/pychess-master-2017-05-28-0819/lib/pychess/widgets/Background.py", line 40, in expose
    cairo_create.set_source_surface(surface, 0, 0)
TypeError: must be cairo.Surface, not None
Traceback (most recent call last):
  File "/tmp/pychess-master-2017-05-28-0819/lib/pychess/Players/PyChess.py", line 11, in <module>
    from pychess.Utils.book import getOpenings  # nopep8
  File "/tmp/pychess-master-2017-05-28-0819/lib/pychess/Players/../../pychess/Utils/book.py", line 7, in <module>
    from pychess.System import conf
  File "/tmp/pychess-master-2017-05-28-0819/lib/pychess/Players/../../pychess/System/conf.py", line 7, in <module>
    from configparser import RawConfigParser
ImportError: No module named configparser

(pychess:32725): Gtk-CRITICAL **: gtk_container_remove: assertion 'gtk_widget_get_parent (widget) == GTK_WIDGET (container) || GTK_IS_ASSISTANT (container)' failed
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

=======================

**Comment by gbtami** [comment] 2017-05-28 21:56
Can you attach the .log file from ~/.local/share/pychess please?

**Comment by BriCra17gh** [comment] 2017-05-28 22:56
github didn't like the .log extension the first time I tried to attach the file so I renamed it to log.txt and even LOG.TXT. Regardless, I get the message below. 

The file is just 3371 ASCII characters. I could copy and paste it here but attaching seems better and is what you asked for. Would you please advise on how to attach?

===

Something went really wrong, and we can’t process that file. 

===

**Comment by gbtami** [comment] 2017-05-29 09:29
I'v installed Linux Mint 17.3 KDE 64-bit in VirtualBox and was able to start pychess. After my latest commit FICS was OK too.
Please update your pychess git and try to completely remove ~/.config/pychess !

update.:
Please update your pychess git , but don't remove config files! If you removed, first reinstall 0.12.4 from .deb and start it at least once.
It will re-create config files. The bug was fixed in latest git, so it should start OK now.

**Comment by BriCra17gh** [comment] 2017-05-30 16:42
I deleted ~/.config/pychess and ran your latest version. pychess does start but there are many warnings, error messages and malfunctions (e.g. can't add engine SF8, unreliable send FICS seek). 

Any suggestions on how to attach the logs and xterm output?

**Comment by gbtami** [comment] 2017-05-30 17:22
Thx but no need to send me .log now if this particular issue is not stands for pychess git. I know I have to fix several problems/bugs in pychess git version before creating first public alpha version. According to https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/ you can attach .zip and .gz files to future issues.
I really appreciate if you continue testing pychess git version and report bugs in new individual issues! I just ask you to use "git clone https://github.com/pychess/pychess.git" and then "git pull" regularly instead of downloading pychess-master.zip

**Comment by BriCra17gh** [comment] 2017-05-30 18:15
Sorry, I think I wasn't clear. I can't test for the bug in this post due to other errors encountered in the current version.

**Comment by gbtami** [comment] 2017-05-30 18:41
Unfortunately subprocess handling (needed to run engines) is not reliable at this moment in git version. Can you confirm that if you set analyzing engines off in preferences hints tab you can play games on FICS? Or you get random hangs with latest git too?

**Comment by gbtami** [comment] 2017-05-31 15:00
Adding SF8 fixed.

**Comment by gbtami** [comment] 2017-06-21 23:05
@BriCra17gh can you make another go for pychess git version please? Several bugs was fixed in last weeks.

**Comment by BriCra17gh** [comment] 2017-06-24 04:19
Sure. Apparently I did something wrong by downloading the full version. I need to learn about the git commands per your previous message. Also, I'm building a new system. Will testing with LM 18.x help or would staying with 17.3 be better?

**Comment by gbtami** [comment] 2017-06-24 06:51
Both can do the job. Just chose what you think is better for you.

**Comment by BriCra17gh** [comment] 2017-06-25 08:19
I used the same OS on the same system as before and couldn't start today's pychess. The errors are below. A few comments and questions:

- I tried to attached a .gz file of the error output as you suggested and got this message: "Something went really wrong, and we can’t process that file." Ideas?

- Using the git commands is much more convenient. Thanks!

- Just curious: what is the problem with downloading the master instead of using the git commands?

===

Warning: eco.db not found, please run pgn2ecodb.sh
Traceback (most recent call last):
  File "./pychess/pychess", line 177, in <module>
    from pychess.Main import PyChess
  File "/tmp/pychess/lib/pychess/Main.py", line 21, in <module>
    from pychess.System.debug import print_obj_referrers, print_muppy_sumary
  File "/tmp/pychess/lib/pychess/System/debug.py", line 15, in <module>
    from pychess.widgets.ionest import game_handler
  File "/tmp/pychess/lib/pychess/widgets/ionest.py", line 14, in <module>
    from pychess.Savers import chessalpha2, epd, fen, pgn, png, database
  File "/tmp/pychess/lib/pychess/Savers/pgn.py", line 16, in <module>
    from pychess.external.scoutfish import Scoutfish
  File "/tmp/pychess/lib/pychess/external/scoutfish.py", line 7, in <module>
    from pexpect.popen_spawn import PopenSpawn
ImportError: No module named 'pexpect.popen_spawn'

===

**Comment by gbtami** [comment] 2017-06-25 08:49
I have no idea about .gz attach error. As a workaround for next time you can upload it to any public place and just copy its link here.

Using the git commands instead of downloading the master is just more convenient IMO. If I commit some fix and you want to test it updating your local repo is just "git pull" and you are ready.

Regarding "ImportError: No module named 'pexpect.popen_spawn'"
I'v just realised in our travis having 14.04 that python3-pexpect is too old (contains no popen_spawn.py at all).
To get the more recent pexpect module from pypi:
sudo pip3 install pexpect
(If you don't have pip3 just install it with "sudo apt install python3-pip")

**Comment by BriCra17gh** [comment] 2017-06-26 04:31
I installed the packages you mentioned. Now pychess starts but it is unusable. Sorry, I know that's vague but there are just so many problems. Did it work on your virtual box?

**Comment by gbtami** [comment] 2017-06-26 22:34
@BriCra17gh thx for all your efforts and patience testing pychess!
Can you describe step-by-step what is "unusable" and what "problems" you noticed please? Without detailed bug reports i can't fix them because git version seems to works for me in VirtualBox.

**Comment by gbtami** [comment] 2017-07-01 13:57
@BriCra17gh if you still interested to test pychess it's time to git pull!
After drop of gbulb glib based main loop to asyncio one seems pychess is stable again! This change also makes pychess usable on Windows again.

**Comment by Jim-Fo** [comment] 2017-07-03 06:17
I pulled a 2017 Jul 2 version. It works a lot better but still has problems. I'll detail them here.

- no sound

- hanging "Connecting to server" if no Internet connection. Hanging remains after restoring Internet. But pychess does connect to FICS if the attempt is stopped and restarted.

- panel layout is hard to use (see attached). E.g., console is unusable despite resizing.

- should I run pgn2ecodb.sh ?

 - should I run create_theme_preview.sh ?

- why is pychess downloading files when I start it?

- several Gtk-WARNING (see logs)

- Segmentation fault (see log1)

- BrokenPipeError (see log2)

- it seems odd that in the second run there are two background processes that finished. In addition to that, I think there should be an error code returned and not success "Done".


![pc1](https://user-images.githubusercontent.com/18003568/27779933-defe0618-5f93-11e7-8021-fdf88e8ecb2c.jpg)


[pychess-err1.txt](https://github.com/pychess/pychess/files/1118551/pychess-err1.txt)

[pychess-err2.txt](https://github.com/pychess/pychess/files/1118554/pychess-err2.txt)

**Comment by BriCra17gh** [comment] 2017-07-03 06:35
I pulled a 2017 Jul 2 version. It works a lot better but still has problems. I'll detail them here.

no sound

hanging "Connecting to server" if no Internet connection. Hanging remains after restoring Internet. But pychess does connect to FICS if the attempt is stopped and restarted.

panel layout is hard to use (see attached). E.g., console is unusable despite resizing.

should I run pgn2ecodb.sh ?

should I run create_theme_preview.sh ?

why is pychess downloading files when I start it?

several Gtk-WARNING (see logs)

Segmentation fault (see log1)

BrokenPipeError (see log2)

it seems odd that in the second run there are two background processes that finished. In addition to that, I think there should be an error code returned and not success "Done".

![pc1](https://user-images.githubusercontent.com/28476737/27780636-1a255ec2-5f98-11e7-9f4d-c2e635e6c2ce.jpg)
[pychess-err1.txt](https://github.com/pychess/pychess/files/1118592/pychess-err1.txt)
[pychess-err2.txt](https://github.com/pychess/pychess/files/1118593/pychess-err2.txt)

**Comment by gbtami** [comment] 2017-07-03 09:40
I'm testing it on Linux Mint 17.3 KDE 64-bit in VirtualBox.

1. I have sound. Check you have packages `gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 gstreamer1.0-pulseaudio` installed please.

2. There is no reconnection (or disconnection detection) feature implemented in pychess.

3. Committed a better default panel layout. Try to `git pull` and `rm ~/.config/pychess/*.xml` please.

4. Run `./pgn2ecodb.sh`
    Released .deb and .rpm packages will do it for users, but running from development source version doesn't.

5. Run `./create_theme_preview.sh`
    Same reason.

6. Pychess is downloading external binary files needed to filter and index .pgn databases. These has no Linux packages yet, so pychess have to download them to `~/.local/share/pychess/engines/`
I plan to implement a dialog window running on start to ask user for permissions.
see: https://github.com/gbtami/chess_db and https://github.com/gbtami/scoutfish

7. All Gtk-WARNING is harmless.

8. Segmentation fault (see log1)
    I have to investigate this one.

9. BrokenPipeError (see log2)
    I have to investigate this one also.

Telling the truth 17.3 ships rather old Gtk (3.14) but pychess needs 3.16 to support panel window DnD docking to reorganize panel layouts after I fixed #1421 
Unfortunately I have no idea how to fix it on Gtk < 3.16 :(

@BriCra17gh thx for the detailed report!

**Comment by gbtami** [comment] 2017-07-03 14:39
10.  background processes
Playing sound with gstreamer caused random crashes. Seems it not works well under asyncio so I decided to run it in another subprocess: https://github.com/pychess/pychess/blob/master/lib/pychess/System/gst_player.py
The second one maybe was pychess own engine https://github.com/pychess/pychess/blob/master/lib/pychess/Players/PyChess.py

**Comment by gbtami** [comment] 2017-07-03 22:45
Fixed #1421 on Gtk < 3.16 in https://github.com/pychess/pychess/commit/87d81f3adf1aeffde8ca03d65ba089fe08005874 so you can set up your preferred layout now with drag and drop notebook tab labels around.

**Comment by gbtami** [comment] 2017-07-23 10:08
Added a dialog to ask for permissions to download external files at startup.

**Comment by gbtami** [comment] 2017-09-18 08:05
@BriCra17gh  can you try if any of problems you reported before still reproducible with 0.99.0 from https://github.com/pychess/pychess/releases please?

**Closed as completed** 2017-09-26 07:02 UTC
Labels: bug, Critical, Need info
