### ISSUE TITLE
Variant Engine randomly freezes under normal usage

### ISSUE THREAD

**Issue by catask** [pychess/pychess#1808] opened 2020-01-02 03:05 UTC
Using the engine seems to random freeze under normal usage. It is stuck on "calculating." It can be solved by exiting the game and reopening or by closing the program and reopening.

![image](https://user-images.githubusercontent.com/58996479/71650266-62c82d00-2cda-11ea-8d5b-b8dc5830a7a9.png)

**Comment by gbtami** [comment] 2020-01-02 07:16
Is it reproducible in any zh game, or happens in this game only?
What exact engine are you using? (Where from was it downloaded?)

If you start pychess with command line arguments: --log-debug --log-viewer
you can see all log messages and engine communication in View -> Log Viewer menu. Maybe that will show some errors or some other useful info.

**Comment by catask** [comment] 2020-01-07 04:41
gbtami,

I have not worked so much on pychess the past week but will keep you updated on the issue. I download the stockfish variant from daniel dugovic github (stockfish 9 variant version).

**Comment by gbtami** [comment] 2020-06-21 21:49
I can't reproduce this, so closing now.
If you can still reproduce feel free to reopen.

**Closed as completed by gbtami** 2020-06-21 21:49 UTC
Labels: bug, Critical
