### ISSUE TITLE
PyChess closing when playing with multiple tabs is not intuitive 

### ISSUE THREAD

**Issue by massimiliano-leoni** [pychess/pychess#1017] opened 2015-09-25 19:18 UTC
... Or, #274 is back!

When I close a game with more than one tab open, it exits.

Steps to reproduce:
1. Open Pychess
2. Start new game, offline is fine. A chessboard appears.
3. Create a new game with Game -> new game -> start game. A new chessboard appears in a new tab.
4. Press the "x" to close the window

Result: Pychess exits instead of going back to main screen.

**Comment by gbtami** [comment] 2015-09-25 19:28
Which "x" do you press exactly? The "x" of 2. game tab, or "x" of the main pychess window? If the latter, it's the intended behaviour in all platform. If the former, then this is a bug.

**Comment by massimiliano-leoni** [comment] 2015-09-25 19:31
The "x" of the main pychess window.
Why is the behaviour different from when there is a single tab?

And what's the reason for this being intended?

**Comment by gbtami** [comment] 2015-09-25 19:56
The "x" of _main_ window in every platform and in every DE used for closing the app. This is the same in pychess with one exception, when only one game is open and there is no tab with "x" for this game available because the user set this in preferences (#274). Am I misunderstand something here?

**Comment by massimiliano-leoni** [comment] 2015-09-25 20:02
Ok, I understand it now.
It does make sense, but then the user experience is "not symmetric" with respect to online gaming, where pressing the "x" button in the "chessboard window" [be it the main window or not] takes the user back to a previous window from where a new game can be started.
Anyway, if that's intended then it should probably stay the way it is :) I just found it slightly unintuitive.

**Comment by gbtami** [comment] 2015-09-25 20:41
I don't understand "not symmetric" here. In FICS (no game started) there are 2 window, the pychess main starter window and the FICS lounge window. If there is only one game (with no tab and "x" on it),  closing with main window "x"  seems unintuitive to go back to main starter instead of FICS lounge window IMO. Am I understand correctly that you are suggesting that clicking on _main_ window "x" should never close the app, but close the games? But isn't it opposite how it is used for in all windowing environments? And why we should do this if games have their own "x" on their tabs?

**Comment by massimiliano-leoni** [comment] 2015-09-26 08:13
I agree that pressing "x" in the first situation you described should take the user back to FICS lounge, I wasn't questioning that.
The lack of symmetry I can see here is the following. When I play online, if I am in the "window with chessboards", be it one or many in tabs, and if I want to clear everything and start a new game then I press the 'x' and Pychess takes me back to a window from where I can start a new game of the kind I was playing. So the user experience here is "window with chessboards -> press "x" -> can start new game".
When playing offline, if I am in the "window with chessboards", be it one or many in tabs, and if I want to clear everything and start a new game then I _cannot_ do it the same way as before: now the user experience is "window with chessboards -> press 'x' -> Pychess exits". [Instead of showing main starter].

I understand that the "window with chessboards" is not the main window in the online game, but is the main window in the offline game, but nevertheless IMHO the user experience should be the same [or I would have thought so].

I hope this makes sense :)

**Comment by gbtami** [comment] 2015-09-28 17:34
The "window with chessboards" is always the main window and clicking on "x" in the main window was always closing the whole PyChess app. The only one exception is the "only 1 game"+"no tabs if only 1 game" case, which was introduced in #274. 

I think what you want is a "Close all" menu functionality, which we don't have yet. Reusing the main window closer "x" for this functionality seems rather rude change from the windowing environment point of view IMO.

**Comment by massimiliano-leoni** [comment] 2015-09-29 18:46
This is not true in online gaming, where the "window with chessboards" is not the main window and closing it takes the user back to the FICS lounge.

I would just do what you described, it wouldn't seem rude IMO. When you start a game from the main starter window, the chessboard takes over the initial window, so pressing the "x" when chessboards are present would just give the window back to the main starter widgets.

**Comment by gbtami** [comment] 2015-09-29 19:43
I think the reason of misunderstanding, that I used "main window" as a programming term. The "main application window" is known as the window which is holding the application main menu and closing it with "x" quits the whole application too.  FICS lounge window is not "main application window" in this regard.
Hmm. Maybe this seems rude only for me, but from users point of view your suggestion can be a useful feature. What do you think about adding it to preferences as "Use main app closer [x] as close all games", with default unchecked?

**Comment by massimiliano-leoni** [comment] 2015-09-29 21:44
I was talking about your same "main window" [let's call it MainWindow]; but still we don't seem to understand each other :D
When playing offline, the chessboards appear in the MainWindow, whereas when playing online the chessboards appear in a Dialog, and the MainWindow lies in the background with the initial PyChess screen. I don't think I ever said that the FICS lounge is the MainWindow.

Your offer is fine, let's put a checkbox :)

Another possible solution would be to have the offline game chessboards appear in a new Dialog.

**Comment by gbtami** [comment] 2015-09-30 10:57
There is no such online/offline difference. When playing games the chessboard not placed in Dialog, but _replaces_ the initial PyChess screen in the MainWindow, as you can see in gamewidget.py line # 800.
Anyhow, I will add a checkbox :)

**Closed as completed** 2015-09-30 12:09 UTC
Labels: enhancement

**Comment by massimiliano-leoni** [comment] 2015-09-30 12:36
Fix confirmed. To me it looks a more natural behaviour now!
Thanks :)

**Comment by gbtami** [comment] 2015-09-30 13:32
Your welcome!
