### ISSUE TITLE
Background processes for the endgames not terminated

### ISSUE THREAD

**Issue by ecrucru** [pychess/pychess#1807] opened 2019-12-28 23:34 UTC
Hello

Solve several endgames, then run `ps aux | grep stockfish` : you have as many sub-processes as played endgames.

Is this behavior indeed unexpected ? Under Windows, there is no such effect.

Regards

**Comment by gbtami** [comment] 2020-06-21 18:25
I can't reproduce this. Is this still an issue?

**Comment by gbtami** [comment] 2020-06-21 21:50
Feel free to reopen if this still an issue for you.

**Comment by ecrucru** [comment] 2020-06-24 22:51
Yes, it still occurs on Debian 10. I don't see the button to reopen this topic :(

The processes are listed even when PyChess is closed. Since it consumes a lot of memory after some endgames are played, I increased Stockfish' hash size to get the following error:

```
OSError: can't allocate memory
engineNest: yield from subprocess.start()
SubProcess: self.proc = yield from asyncio.wait_for(create, TIME_OUT_SECOND)
```

A manual kill of the remaining processes restored the memory at a normal level.

**Comment by Arunachala-Ramana** [comment] 2020-07-16 05:02
I think this error is there in ubuntu as well. After i play a lot of lessons/endgames/puzzles, and then open system monitor and check, it shows a whole of lot of stockfish processes running :( and then I manually kill it

**Comment by remiDInria** [comment] 2021-07-23 14:35
Same issue on Ubuntu 21.04 ,  Steinitz 1.0.3
After online gaming as guest, many pychess and stockfish processes still alive once pychess windows closed.
Have to kill them manually.

**Comment by remiDInria** [comment] 2021-09-29 14:37
Since to be OK if you manually close every opened game before closing pychess main window.

**Comment by ItsBlinkHere** [comment] 2021-11-20 04:27
Same problem on manjaro linux as well. UCI engine keeps running after game completed and tab or even the entire PyChess app is closed.

**Comment by remiDInria** [comment] 2021-11-22 07:51
More than 1 pychess process running creates an additional related issue: FICS bans users out because of too many connections at the same time with same ip.

**Comment by leotada** [comment] 2023-03-16 14:14
This is the same as #1949 , and still occurring because had no release after this. @gbtami

**Comment by hartwork** [comment] 2023-03-16 17:06
I had a quick look and for Git `master` I can confirm that per new endgame played, the number of Stockfish processes increased but given that every new endgame also gets a new tab and that the number of stockfish processes decreases (to 1) when closing all endgame tabs, I'm not sure much of a bug this is. After closing PyChess, all Stockfish processes are gone. This is on Linux.

Could you help me understand the scope of the problem better?

**Comment by gbtami** [comment] 2023-03-16 17:13
@hartwork possible we should push out a new 1.1 alpha release as soon as possible (as you suggested) to let people confirm old bugs and report new bugs :)

**Comment by hartwork** [comment] 2023-03-16 17:22
@gbtami good point. I also tried with PyChess 1.0.3 now and the behavior seems different a bit, closing all tabs will keep more stockfish around than with Git `master` it seems. So a new release would indeed help in the bug tracker also :+1:

**Closed as completed** 2023-03-24 21:00 UTC
Labels: bug
